### ISSUE TITLE
musl dependency?

### ISSUE THREAD

**Issue by ameir** [keilerkonzept/aws-secretsmanager-env#61]
This works fine in Alpine, but in amazonlinux:2, the following error is returned:
```
bash-4.2# /usr/local/bin/aws-secretsmanager-env -h
bash: /usr/local/bin/aws-secretsmanager-env: /lib/ld-musl-x86_64.so.1: bad ELF interpreter: No such file or directory
```

**Comment by sgreben** [comment]
Ohh, I think we're pulling in a libc dependency via `net` somewhere. I'm looking into it now.
